### ISSUE TITLE
Not an issue, but just a compliment

### ISSUE THREAD

**Issue by HelloAnneKim** [nhynes/pbean#1]
We're using a very similar idea for Pika Dinner next week :)

**Comment by nhynes** [comment]
That's fantastic! It's a great honor :) Would you mind sharing the results?

**Comment by HelloAnneKim** [comment]
Yes! You could even come to dinner! Wednesday July 27th at 18:30!  Our tentative menu is bread stuffed with some kind of nutritious bean paste, dumplings, quinoa salad bowl, pie or some other dessert, and your shake (or a variant of it).

**Comment by nhynes** [comment]
I'll definitely try to make it! Will you be prepping pbean the day before so that it has time to chill? In fact, if you'd like, I can stop by on Tuesday (if it's not raining) and help whip up a batch.

**Comment by HelloAnneKim** [comment]
OMG IT WOULD BE AN HONOR, NICK HYNES

**Comment by nhynes** [comment]
Solid rendition of pbean! My only recommendation, really, would be to use mass instead of volumetric measurements. Thanks again!
